/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.Controller.PomodoroController;
import org.example.Model.PomodoroModel;
import org.example.View.PomodoroView;
import org.example.View.Components.ButtonMenue;
import org.example.View.Components.PlayButtonHBox;
import org.example.View.Components.TimeRing;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import javafx.stage.StageStyle;


public class PomodoroTimerApp extends Application{

    PomodoroModel pomodoroModel = new PomodoroModel(25 * 60);
    PomodoroView pomodoroView = new PomodoroView();
    PomodoroController pomodoroController = new PomodoroController(pomodoroModel, pomodoroView);

    
    
    
    @Override
    public void start(Stage primaryStage) throws Exception {

        

        



     


        Scene scene = new Scene(pomodoroView, 288, 409);
        scene.getStylesheets().add(getClass().getResource("/style/style.css").toExternalForm());


        primaryStage.setTitle("Pomodoro Timer");
        primaryStage.setResizable(false);
        primaryStage.initStyle(StageStyle.UTILITY);
        primaryStage.setScene(scene);
        primaryStage.show();

    }

    public static void main(String[] args) {
        launch(args);
    }

   
}
