/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.Controller.PomodoroController;
import org.example.Model.PomodoroModel;
import org.example.View.PomodoroView;

public class PomodoroTimerApp {
    

    public static void main(String[] args) {
        PomodoroModel pomodoroModel = new PomodoroModel();
        PomodoroView pomodoroView = new PomodoroView();
        PomodoroController pomodoroController = new PomodoroController(pomodoroModel, pomodoroView);
    }
}
